-- Schema for VibeCodedApps user_favorites
CREATE TABLE IF NOT EXISTS public.user_favorites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    app_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT user_favorites_user_id_app_id_key UNIQUE (user_id, app_id)
);

CREATE INDEX IF NOT EXISTS idx_user_favorites_user_id ON public.user_favorites USING btree (user_id);

ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'user_favorites_select') THEN
        CREATE POLICY user_favorites_select ON public.user_favorites FOR SELECT USING ((auth.uid() = user_id));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'user_favorites_insert') THEN
        CREATE POLICY user_favorites_insert ON public.user_favorites FOR INSERT WITH CHECK ((auth.uid() = user_id));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'user_favorites_delete') THEN
        CREATE POLICY user_favorites_delete ON public.user_favorites FOR DELETE USING ((auth.uid() = user_id));
    END IF;
END
$$;
