-- Schema for VibeCodedApps user_favorites
CREATE TABLE IF NOT EXISTS public.user_favorites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    app_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT user_favorites_user_id_app_id_key UNIQUE (user_id, app_id)
);

CREATE INDEX IF NOT EXISTS idx_user_favorites_user_id ON public.user_favorites USING btree (user_id);

ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'user_favorites_select') THEN
        CREATE POLICY user_favorites_select ON public.user_favorites FOR SELECT USING ((auth.uid() = user_id));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'user_favorites_insert') THEN
        CREATE POLICY user_favorites_insert ON public.user_favorites FOR INSERT WITH CHECK ((auth.uid() = user_id));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'user_favorites_delete') THEN
        CREATE POLICY user_favorites_delete ON public.user_favorites FOR DELETE USING ((auth.uid() = user_id));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'user_favorites_service_role') THEN
        CREATE POLICY user_favorites_service_role ON public.user_favorites FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
END
$$;

-- Schema for VibeCodedApps user_app_data (Cross-Device Storage Sync)
CREATE TABLE IF NOT EXISTS public.user_app_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    app_id text NOT NULL,
    data_key text NOT NULL,
    data_value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT user_app_data_user_app_key UNIQUE (user_id, app_id, data_key)
);

CREATE INDEX IF NOT EXISTS idx_user_app_data_lookup ON public.user_app_data (user_id, app_id);

ALTER TABLE public.user_app_data ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'user_app_data_all') THEN
        CREATE POLICY user_app_data_all ON public.user_app_data FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'user_app_data_service_role') THEN
        CREATE POLICY user_app_data_service_role ON public.user_app_data FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
END
$$;

-- Ensure service_role has BYPASSRLS
ALTER ROLE service_role BYPASSRLS;

-- Grant permissions to PostgREST roles
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO anon, authenticated, service_role;

