CREATE TABLE IF NOT EXISTS public.categories (
    id text PRIMARY KEY,
    title text NOT NULL,
    icon text NOT NULL,
    color text NOT NULL DEFAULT 'emerald',
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.apps (
    id text PRIMARY KEY,
    category_id text REFERENCES public.categories(id) ON DELETE SET NULL,
    name text NOT NULL,
    "desc" text NOT NULL,
    icon text NOT NULL,
    url text NOT NULL,
    action text NOT NULL DEFAULT 'Uygulamayı Aç',
    status text NOT NULL DEFAULT 'active',
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.apps ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'categories_select_all') THEN
        CREATE POLICY categories_select_all ON public.categories FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'apps_select_all') THEN
        CREATE POLICY apps_select_all ON public.apps FOR SELECT USING (true);
    END IF;
END
$$;

INSERT INTO public.categories (id, title, icon, color, sort_order) VALUES ('saglik', 'Sağlık', '🏥', 'undefined', 0) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, icon=EXCLUDED.icon, color=EXCLUDED.color, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('nobetci-eczane', 'saglik', 'İzmir Nöbetçi Eczane Radarı', 'İzmir BB Açık Veri API''si ve OpenStreetMap ile canlı konum, en yakın 5 nöbetçi eczane, mesafe ve tek tıkla arama/yol tarifi.', '💊', '/nobetci-eczane', 'Eczaneleri Bul', 0) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('ilac-rehberi', 'saglik', 'İlaç & Prospektüs Rehberi', 'U.S. FDA ve resmi farmakope veri tabanı ile etken maddeler, prospektüs özeti, kullanım uyarıları ve açık bildirilmiş yan etki analitiği.', '💊', '/ilac-rehberi', 'İlacı İncele', 1) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('kas-anatomisi', 'saglik', 'İnteraktif Kas Anatomisi & Egzersiz', 'workout-cool ve Wger verileriyle interaktif vücut kas haritası, hedeflenen egzersizler, doğru form rehberi ve duruş terapisi.', '🏋️', '/kas-anatomisi', 'Anatomiyi Keşfet', 2) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('klinik-arastirma', 'saglik', 'Klinik Araştırmalar Radarı', 'NIH ClinicalTrials.gov v2 API ile kanser, diyabet ve nörolojideki aktif klinik deneyler, faz aşamaları ve deneysel tedaviler.', '🔬', '/klinik-arastirma', 'Çalışmaları İncele', 3) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('dso-saglik', 'saglik', 'Küresel Sağlık Atlası (DSÖ)', 'Dünya Sağlık Örgütü resmi verileriyle Türkiye ve 190+ ülkenin beklenen yaşam süresi, aşılanma ve mortalite göstergeleri.', '🌐', '/dso-saglik', 'Göstergeleri İncele', 4) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.categories (id, title, icon, color, sort_order) VALUES ('cografya-doga', 'Coğrafya, Doğa & Çevre', '🌱', 'undefined', 1) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, icon=EXCLUDED.icon, color=EXCLUDED.color, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('tarim-hava', 'cografya-doga', 'Akıllı Tarım & Zirai Hava', 'Open-Meteo ile toprak nemi/sıcaklığı derinlikleri, don riski erken uyarı sistemi, evapotranspirasyon ve sulama tavsiyeleri.', '🌾', '/tarim-hava', 'Paneli Başlat', 0) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('karbon-metre', 'cografya-doga', 'Web Karbon Ayak İzi', 'Web sitelerinin sayfa yükleme başına CO2 salımı, yeşil hosting doğrulaması ve gömülebilir dinamik eko-rozet.', '🌱', '/karbon-metre', 'Ölçümü Başlat', 1) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('doga-sesleri', 'cografya-doga', 'Kuş Sesi Dedektifi', 'iNaturalist biyoakustik arşivi ile 500.000+ yabani kuş sesi, canlı spektrum ses dalgası ve mini tahmin testi.', '🐦', '/doga-sesleri', 'Sesleri Dinle', 2) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('cografya-atlasi', 'cografya-doga', 'Küresel Coğrafya Atlası', 'REST Countries API ile 250 dünya ülkesinin bayrakları, başkentleri, nüfusu, dilleri ve sınır komşuları.', '🌍', '/cografya-atlasi', 'Atlası İncele', 3) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('hava-kalitesi', 'cografya-doga', 'Canlı Hava Kalitesi Radarı', 'Dünya şehirlerinin canlı PM2.5, PM10, NO2 kirlilik seviyeleri, Avrupa AQI endeksi ve sağlık tavsiyeleri.', '💨', '/hava-kalitesi', 'Havayı Ölç', 4) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('sehir-bisiklet', 'cografya-doga', 'Şehir Bisiklet Rehberi', 'CityBikes API ile 400+ dünya metropolünde canlı bisiklet durakları, boş bisiklet ve park yuvası haritası.', '🚲', '/sehir-bisiklet', 'Durakları Gör', 5) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('deniz-dalga', 'cografya-doga', 'Mavi Rota: Dalga & Sörf Radarı', 'Open-Meteo Marine API ile Ege, Akdeniz ve Karadeniz kıyılarında canlı dalga boyu, periyot ve sörf uygunluğu.', '🌊', '/deniz-dalga', 'Denizi İncele', 6) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.categories (id, title, icon, color, sort_order) VALUES ('uzay-bilim', 'Uzay & Bilim', '🧬', 'undefined', 2) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, icon=EXCLUDED.icon, color=EXCLUDED.color, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('molekul-studyosu', 'uzay-bilim', '3D Molekül Stüdyosu', 'PubChem 3D Conformer ve 3Dmol.js WebGL motoruyla kimyasalların ve ilaçların 3D atomik modellemesi.', '🧬', '/molekul-studyosu', 'Stüdyoyu Başlat', 0) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('iss-takip', 'uzay-bilim', 'Where is ISS? Uzay Radarı', 'Uluslararası Uzay İstasyonu''nun (ISS) anlık enlem, boylam, 27.600 km/s yörünge hızı ve canlı haritası.', '🛰️', '/iss-takip', 'İstasyonu Takip Et', 1) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('sayilar-atlasi', 'uzay-bilim', 'Sayılar Atlası & Matematik', 'Numbers motoru ile sayıların asallık, Fibonacci, bölen analizi, ikili kodları ve tarihteki gizemli gerçekleri.', '🧮', '/sayilar-atlasi', 'Sayıyı Keşfet', 2) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('nobel-arsivi', 'uzay-bilim', 'Nobel Ödülleri Arşivi', 'Nobel Vakfı resmi API''si ile 1901''den günümüze bilim insanları, çığır açan keşifler ve edebiyat ödülleri.', '🎖️', '/nobel-arsivi', 'Arşivi İncele', 3) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.categories (id, title, icon, color, sort_order) VALUES ('sanat-tarih-edebiyat', 'Sanat, Tarih & Edebiyat', '🎨', 'undefined', 3) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, icon=EXCLUDED.icon, color=EXCLUDED.color, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('sanat-galerisi', 'sanat-tarih-edebiyat', 'Global Sanat Galerisi', 'The Met Museum dijital arşivi ile usta ressamlar, derin yakınlaştırma (deep zoom) ve kişisel sanat sergisi.', '🎨', '/sanat-galerisi', 'Galeriyi Gez', 0) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('klasik-kutuphane', 'sanat-tarih-edebiyat', 'Dijital Kütüphane', 'Project Gutenberg ile 70.000+ dünya klasiği, tarayıcı içi e-kitap okuyucu, yer imleri ve kişisel kitaplık.', '📖', '/klasik-kutuphane', 'Okumaya Başla', 1) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('tatil-takvimi', 'sanat-tarih-edebiyat', 'Küresel Tatil Takvimi', '100+ ülkenin resmi tatilleri, eşzamanlı çoklu ülke karşılaştırması, akıllı köprü izin fırsatları ve iCal desteği.', '📅', '/tatil-takvimi', 'Takvimi Aç', 2) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('unesco-miras', 'sanat-tarih-edebiyat', 'UNESCO Dünya Mirası Atlası', 'Göbeklitepe''den Machu Picchu''ya dünya mirası alanları, fotoğrafları, kabul yılları ve harita konumları.', '🏛️', '/unesco-miras', 'Mirasları Keşfet', 3) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('sesli-kitap', 'sanat-tarih-edebiyat', 'Sesli Kütüphane (LibriVox)', 'LibriVox açık kamu malı arşivi ile dünya edebiyatı klasiklerinin seslendirilmiş kayıtları ve ses çaları.', '🎧', '/sesli-kitap', 'Kitap Dinle', 4) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('siir-antolojisi', 'sanat-tarih-edebiyat', 'Şiir Vahası: Şiir Antolojisi', 'PoetryDB açık arşivi ile Shakespeare, Poe, Dickinson ve usta şairlerin 3.000+ eseri ve tipografik okuyucu.', '📜', '/siir-antolojisi', 'Şiirleri Oku', 5) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.categories (id, title, icon, color, sort_order) VALUES ('oyun', 'Oyun', '🎮', 'undefined', 4) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, icon=EXCLUDED.icon, color=EXCLUDED.color, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('kultur-arena', 'oyun', 'Kültür Arenası & Trivia', 'Solo yarışma, 1v1 canlı düello odaları, başarımlar, XP seviyeleri ve detaylı karşılaşma geçmişi.', '🌍', '/kultur-arena', 'Arenaya Gir', 0) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('oyun-radar', 'oyun', 'Steam & Epic Fırsat Avcısı', 'CheapShark & GamerPower ile anlık büyük indirimler, %100 ücretsiz kalıcı hediyeler ve istek listesi.', '🏷️', '/oyun-radar', 'Fırsatları Yakala', 1) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('oyun-arsivi', 'oyun', 'Oyun Keşif Kütüphanesi', 'FreeToGame ve açık oyun veritabanı ile PC ve tarayıcı tabanlı yüzlerce oyun, tür filtreleri ve detaylar.', '🕹️', '/oyun-arsivi', 'Oyunları Keşfet', 2) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('oyun-rekorlari', 'oyun', 'Speedrun Oyun Rekorları', 'Speedrun.com açık veritabanı ile popüler video oyunlarının dünya rekoru bitirme süreleri ve liderleri.', '⚡', '/oyun-rekorlari', 'Rekorları Gör', 3) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.categories (id, title, icon, color, sort_order) VALUES ('populer-kultur', 'Popüler Kültür & Eğlence', '🍿', 'undefined', 5) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, icon=EXCLUDED.icon, color=EXCLUDED.color, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('dizi-rehberi', 'populer-kultur', 'Dizi & Sezon Takipçisi', 'IMDb & TVmaze ile bölüm bazlı sezon takibi, izleme ajandası ve IMDb linkiyle özel yapım ekleme.', '🎬', '/dizi-rehberi', 'Rehberi Başlat', 0) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('sozden-sarkiya', 'populer-kultur', 'Sözden Şarkıya', 'LRCLIB & iTunes ile aklınızda kalan sözlerden şarkı tespiti, tam şarkı sözleri ve 30 saniyelik ses önizlemesi.', '🎵', '/sozden-sarkiya', 'Dedektifi Başlat', 1) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('lezzet-atolyesi', 'populer-kultur', 'Lezzet Atölyesi', 'TheMealDB, Forkify ve TheCocktailDB ile mutfak & miksoloji barı, malzeme arama ve tarif defteri.', '🍹', '/lezzet-atolyesi', 'Atölyeyi Başlat', 2) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('gida-alerji', 'populer-kultur', 'Gıda Dedektifi & Alerjen Kalkanı', 'Open Food Facts ile barkod tarama, Nutri-Score, besin değerleri ve kişisel alerji uyarısı.', '🏷️', '/gida-alerji', 'Ürünü İncele', 3) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('dunya-radyo', 'populer-kultur', 'Dünya Radyo Kulesi', 'Radio Browser API ile 30.000+ küresel canlı radyo yayını, ülke ve müzik türü filtreleri ve Web Audio çaları.', '📻', '/dunya-radyo', 'Radyoyu Dinle', 4) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('evcil-rehber', 'populer-kultur', 'Evcil Dostlar Ansiklopedisi', 'TheCatAPI & Dog CEO ile 150+ kedi ve köpek ırkı, mizaç analizi, yaşam süresi ve çocuk dostluğu rehberi.', '🐾', '/evcil-rehber', 'Irkları Keşfet', 5) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('gitar-akor', 'populer-kultur', 'Akustik: Gitar Akor & Tab', 'Gitar akor şemaları, parmak basış rehberi, canlı transpoze (ton değiştirici) ve otomatik sayfa kaydırma.', '🎸', '/gitar-akor', 'Stüdyoyu Başlat', 6) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.categories (id, title, icon, color, sort_order) VALUES ('finans-piyasa', 'Finans & Piyasa', '📊', 'undefined', 6) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, icon=EXCLUDED.icon, color=EXCLUDED.color, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('doviz-cevirici', 'finans-piyasa', 'Anlık Döviz Çevirici', 'Frankfurter & ECB resmi kurları ile 30+ para birimi, anlık çapraz kur çevirisi, Chart.js trend grafikleri ve getiri analizi.', '💱', '/doviz-cevirici', 'Çeviriciyi Başlat', 0) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('kuresel-gostergeler', 'finans-piyasa', 'Küresel Refah Göstergesi', 'World Bank resmi verileriyle son 30 yıllık GSYİH, ömür, enflasyon, enerji ve refah endeksi analizi.', '📊', '/kuresel-gostergeler', 'Göstergeleri İncele', 1) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('kripto-trend', 'finans-piyasa', 'Kripto Trend & Piyasa Radarı', 'CoinGecko API ile anlık kripto para fiyatları, 24 saatlik değişimler, trend tokenlar ve dönüştürücü.', '🪙', '/kripto-trend', 'Piyasayı İzle', 2) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.categories (id, title, icon, color, sort_order) VALUES ('gelistirici-araclari', 'Geliştirici Araçları', '💻', 'undefined', 7) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, icon=EXCLUDED.icon, color=EXCLUDED.color, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('github-analitik', 'gelistirici-araclari', 'GitHub Profil Analitiği', 'Repo yıldızları, dil dağılımı, geliştirici kıdemi ve profillere gömülebilir dinamik SVG kartı üretimi.', '<i class="fa-brands fa-github" style="color: rgb(0, 0, 0);"></i>', '/github-analitik', 'Profili İncele', 0) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('dns-kontrol', 'gelistirici-araclari', 'DNS Kontrol & Ağ Teşhisi', 'Cloudflare & Google DoH ile anlık A, MX, TXT, NS kayıtları, küresel yayılım, SPF/DMARC ve gecikme testi.', '🌐', '/dns-kontrol', 'Kayıtları Çözümle', 1) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('sizinti-kontrol', 'gelistirici-araclari', 'Sızıntı Kontrolü & Güvenlik', 'HaveIBeenPwned k-Anonymity (SHA-1) protokolü ile sıfır bilgi garantili şifre sızıntı denetimi ve entropi analizi.', '🛡️', '/sizinti-kontrol', 'Güvenliği Test Et', 2) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('ip-konum', 'gelistirici-araclari', 'IP Coğrafi Konum & İstihbarat', 'ip-api ve SSRF korumalı altyapıyla IP lokasyonu, İnternet Servis Sağlayıcı (ISP), ASN ve harita koordinatları.', '📍', '/ip-konum', 'Konumu Bul', 3) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('renk-studyosu', 'gelistirici-araclari', 'Harmoni: Renk & Kontrast Stüdyosu', 'The Color API ile analog, komplementer renk şemaları, WCAG erişilebilirlik kontrast analizi ve CSS dışa aktarımı.', '🎨', '/renk-studyosu', 'Palet Üret', 4) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('http-status', 'gelistirici-araclari', 'HTTP Sözlüğü & Cihaz Röntgeni', '1xx-5xx HTTP durum kodları referansı, çözüm rehberi, cURL örnekleri ve canlı donanım/GPU parmak izi analizi.', '💻', '/http-status', 'Teşhisi Aç', 5) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
INSERT INTO public.categories (id, title, icon, color, sort_order) VALUES ('web-araclari', 'Web Araçları', '🛠️', 'undefined', 8) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, icon=EXCLUDED.icon, color=EXCLUDED.color, sort_order=EXCLUDED.sort_order;
INSERT INTO public.apps (id, category_id, name, "desc", icon, url, action, sort_order) VALUES ('qr-studio', 'web-araclari', 'QR Studio', 'Vektörel, logolu, gradyan renkli ve çok formatlı (URL, Wi-Fi, vCard) profesyonel QR üretici.', '📱', '/qr-studio', 'Stüdyoyu Başlat', 0) ON CONFLICT (id) DO UPDATE SET category_id=EXCLUDED.category_id, name=EXCLUDED.name, "desc"=EXCLUDED."desc", icon=EXCLUDED.icon, url=EXCLUDED.url, action=EXCLUDED.action, sort_order=EXCLUDED.sort_order;
